### ISSUE TITLE
[Feature Proposal] Include Policy violation metrics in deciding build failures.

### ISSUE THREAD

**Issue by iamrahul127** [gsoft-inc/azure-pipelines-dependency-track#22]
Following metrics are currently not included in deciding build pipeline failure. We would like to include them as we would like to stop PR from merging in case of policy failures. 

policyViolationsFail
policyViolationsWarn
policyViolationsInfo
policyViolationsTotal

[Pull request](https://github.com/gsoft-inc/azure-pipelines-dependency-track/pull/21) is already created which solves this problem. 
Request you to review, test and merge in case you think it's good feature to include

**Comment by iamrahul127** [comment]
@yohanb @Zargath If you can prioritize and help.

**Comment by yohanb** [comment]
Hi @iamrahul127 ,
your PR has been merged. Thanks for the contribution!

**Comment by iamrahul127** [comment]
Hi @yohanb,
May I know when are you planning to release new version of this extension? How do I get notification when it's done?
