### ISSUE TITLE
Occasionally giving errors uploading SBOM

### ISSUE THREAD

**Issue by danielpof** [gsoft-inc/azure-pipelines-dependency-track#28]
On our dotnet pipelines we're getting ocasional errors submiting the SBOM, the error in the pipeline looks like this:

```log
2022-11-28T13:19:57.4206314Z ##[section]Starting: Submit BOM
2022-11-28T13:19:57.4216287Z ==============================================================================
2022-11-28T13:19:57.4216822Z Task         : Upload BOM to Dependency Track
2022-11-28T13:19:57.4217120Z Description  : Upload a BOM file to Dependency Track platform.
2022-11-28T13:19:57.4217562Z Version      : 1.12.0
2022-11-28T13:19:57.4217817Z Author       : Edouard Shaar
2022-11-28T13:19:57.4218012Z Help         : 
2022-11-28T13:19:57.4218287Z ==============================================================================
2022-11-28T13:19:57.7948413Z Reading BOM from location: /home/vsts/work/_temp/bom.xml
2022-11-28T13:19:57.7951998Z Starting BOM upload to Dependency Track at url: https://dtrack-api.anova.dev/
2022-11-28T13:19:58.6143782Z Uploading the BOM succeeded! Token: 458055c0-7b9c-4de7-a6c6-365a8b81333d
2022-11-28T13:19:58.6151594Z Waitting for Dependency Track to finish processing the BOM.
2022-11-28T13:20:00.6199347Z Polling Dependency Track for update.
2022-11-28T13:20:01.0774893Z Waitting for metrics to refresh.
2022-11-28T13:20:03.5113973Z Polling Dependency Track for update.
2022-11-28T13:20:03.9325056Z Finished task execution with error - SyntaxError: Unexpected end of JSON input
2022-11-28T13:20:03.9329826Z ##[error]Unexpected end of JSON input
2022-11-28T13:20:03.9476065Z ##[error]Exit code 1 returned from process: file name '/home/vsts/agents/2.213.2/externals/node10/bin/node', arguments '"/home/vsts/work/_tasks/upload-bom-dtrack-task_8703d74d-71e5-4666-ae55-b26df77f2ad5/1.12.0/task.js"'.
2022-11-28T13:20:03.9481678Z ##[section]Finishing: Submit **BOM**
```

Looking serverside on the dependency-track api endpoint log we've noticed several of these warnings, while it seems to happen when submitting from the pipeline task, downloading the SBOM artifact and manually submiting doesn't seem to cause the same error.

```log
2022-11-28 14:43:26,240 WARN [BomUploadProcessingTask] The BOM uploaded is not in a supported format. Supported formats include CycloneDX XML and JSON
```

I thought it could be due to enconding but seems that has been [resolved on the API side](https://github.com/DependencyTrack/dependency-track/issues/1214) so unsure what might be causing the Warnings and ocasional errors.

**Comment by Zargath** [comment]
Hi @daniel-anova,

Can you share with me the version of Dependency Track you are using? I can see where in the extension's code this error could be mishandled, but I would like to test it to be sure.

Thanks!

**Comment by danielpof** [comment]
Hi @Zargath 

Since this issue begun, we've upgraded to 4.6.3 release. previously we were on 4.5.0. The warnings server side still showing up, as for the pipeline failure it's ocasional and so far I haven't received reports of it happening again.

**Comment by Zargath** [comment]
I will add some error handling around where I believe the issue is. With any luck, I will have some time to do that tomorrow. Does both uploading the BOM via the pipeline and manually uploading it to Dependency Track both give an error even if they are not the same error?

**Comment by Zargath** [comment]
Hi @daniel-anova,

I've added some error handling in the latest release around the area of code I suspect is having the issue along with some well needed dependency updates. I also noticed cyclonedx-bom is no longer supported. I don't know what you are using to generate your BOM, but it might be worth validating if your using an updated version there.

Let me know if you receive an updated error message or if that solves the issue.

Thanks!

**Comment by danielpof** [comment]
We're using [CycloneDX dotnet tool](https://github.com/CycloneDX/cyclonedx-dotnet) latest version. When you say `cyclonedx-bom` is no longer supported do you mean a specific tool? Since dependency-track still supports cyclonedx booms as I can upload them manuall.

```
2022-12-05 09:40:22,799 WARN [BomUploadProcessingTask] The BOM uploaded is not in a supported format. Supported formats include CycloneDX XML and JSON
```

I have checked latest run and we're still seeing the warning message when updating BOM from pipeline and the project BOM wasn't updated (still showing last submission as October 11th so it's silently failing).

![image](https://user-images.githubusercontent.com/71904581/205607922-d38d17e6-9628-4689-9a72-3592302d779d.png)

Using dependency Track to upload the BOM.xml generated by the pipeline (we save it as an artifact before using the task to upload) updates the BOM giving no warning about unsupported format.

![image](https://user-images.githubusercontent.com/71904581/205608013-bbbd4926-d725-402b-a305-80f597aedb1e.png)

Looking at the Web interface it call the same endpoint `/api/v1/bom` as the task with the payload being `content-type: multipart/form-data; boundary=----WebKitFormBoundaryFnGnEpaQy3BH4MDm`.

Form Data:

```
------WebKitFormBoundaryFnGnEpaQy3BH4MDm
Content-Disposition: form-data; name="project"

b11fa36b-5764-484a-9f7d-00e8eaad06ee
------WebKitFormBoundaryFnGnEpaQy3BH4MDm
Content-Disposition: form-data; name="bom"; filename="bom (3).xml"
Content-Type: text/xml


------WebKitFormBoundaryFnGnEpaQy3BH4MDm--
```

Not very knowledgeable in web dev but would that be the equivalent to [what the task is doing](https://github.com/gsoft-inc/azure-pipelines-dependency-track/blob/ad70e26d81a19235e576b6613adac83ec96e52e7/UploadBOM/src/dtrackClient.js#L24)?

**Comment by Zargath** [comment]
> We're using [CycloneDX dotnet tool](https://github.com/CycloneDX/cyclonedx-dotnet) latest version. When you say cyclonedx-bom is no longer supported do you mean a specific tool?

That's the proper way of generating a BOM. I was referring to my old example that was using this https://www.npmjs.com/package/@cyclonedx/bom, which is no longer what it used to be. It's a meta package instead of a command line tool now.

Can you give me the full task output, like you did in the initial post? It would help me contextualise the message.

> Looking at the Web interface it call the same endpoint /api/v1/bom as the task with the payload being content-type: multipart/form-data; boundary=----WebKitFormBoundaryFnGnEpaQy3BH4MDm.

The Azure DevOps task does not use the same endpoint. The Dtrack API provides both `POST /v1/bom` and `PUT /v1/bom`. We are using the PUT because it allows us to pass the BOM using base 64 encoding. Like Dependency Track does [here](https://github.com/DependencyTrack/dependency-track/blob/81a4f0e2f101a343e1b4e431729b93d83b309617/src/test/java/org/dependencytrack/integration/ApiClient.java#L68).

**Comment by danielpof** [comment]
> Can you give me the full task output, like you did in the initial post? It would help me contextualise the message.

Since we've upgrade to 4.6.3 release I have yet to to see an error message on the pipeline side, so the log doesn't say much:

```log
2022-12-12T10:15:12.7967643Z ##[section]Starting: Submit BOM
2022-12-12T10:15:12.7980702Z ==============================================================================
2022-12-12T10:15:12.7981079Z Task         : Upload BOM to Dependency Track
2022-12-12T10:15:12.7981374Z Description  : Upload a BOM file to Dependency Track platform.
2022-12-12T10:15:12.7981644Z Version      : 1.13.0
2022-12-12T10:15:12.7981855Z Author       : Edouard Shaar
2022-12-12T10:15:12.7982047Z Help         : 
2022-12-12T10:15:12.7982318Z ==============================================================================
2022-12-12T10:15:13.4103035Z Reading BOM from location: /home/vsts/work/_temp/bom.xml
2022-12-12T10:15:13.4107481Z Starting BOM upload to Dependency Track at url: https://dtrack-api.anova.dev/
2022-12-12T10:15:15.1832189Z Uploading the BOM succeeded! Token: 1a7bfb73-03fa-4c88-b2d9-56daf8b89ef0
2022-12-12T10:15:15.1834412Z Waitting for Dependency Track to finish processing the BOM.
2022-12-12T10:15:16.9869907Z Polling Dependency Track for update.
2022-12-12T10:15:17.4045028Z Waitting for metrics to refresh.
2022-12-12T10:15:20.0289073Z Polling Dependency Track for update.
2022-12-12T10:15:20.4543315Z Last date of BOM import: Mon Dec 05 2022 09:57:21 GMT+0000 (Coordinated Universal Time)
2022-12-12T10:15:20.4544578Z Last date of Metrics update: Mon Dec 12 2022 09:37:21 GMT+0000 (Coordinated Universal Time)
2022-12-12T10:15:20.4545407Z Current Vulnerability Count:
2022-12-12T10:15:20.4548573Z Critical: 0
2022-12-12T10:15:20.4549131Z High:3
2022-12-12T10:15:20.4549623Z Medium: 2
2022-12-12T10:15:20.4550067Z Low: 0
2022-12-12T10:15:20.4550513Z Unassigned: 0
2022-12-12T10:15:20.4550976Z Suppressed: 3
2022-12-12T10:15:20.4551463Z Current Policy Violation Count:
2022-12-12T10:15:20.4551943Z Fail: 0
2022-12-12T10:15:20.4552381Z Warn:0
2022-12-12T10:15:20.4552818Z Info: 646
2022-12-12T10:15:20.4553263Z Total: 646
2022-12-12T10:15:20.4553769Z Finished task execution successfully!
2022-12-12T10:15:20.4599716Z ##[section]Finishing: Submit BOM
```

The warnings however still show dependency-track api server logs:

```log
2022-12-12 10:14:22,048 INFO [OssIndexAnalysisTask] Analyzing 1 component(s)
2022-12-12 10:14:29,373 INFO [OssIndexAnalysisTask] Analyzing 4 component(s)
2022-12-12 10:15:15,009 WARN [BomUploadProcessingTask] The BOM uploaded is not in a supported format. Supported formats include CycloneDX XML and JSON
```

And as noted before the date of last BOOM import is not updated.

**Comment by iamrahul127** [comment]
I am also facing this issue. I am on DT 4.6.2 version. It's strange that I am can upload same BOM file using DT's BOM upload functionality without any error and DT is happy about it. 
Do you think there is some problem the way we are uploading BOM?

PFA BOM which is not working.

[bom.txt](https://github.com/gsoft-inc/azure-pipelines-dependency-track/files/10245498/bom.txt)

**Comment by Zargath** [comment]
Thank you for providing your BOM @iamrahul127! I will attempt to reproduce the issue on my side using your BOM. I haven't ruled out the possibility that the issue is in the way the extension uploads the BOM to Dependency Track. I will continue my investigation and give an update here when I can.

**Comment by iamrahul127** [comment]
Thank you. Waiting desperately to know what's going wrong here. Initially I thought it's happening because of non-ASCII characters in BOM but then it should be reproducible through DTs upload BOM functionality. 

My reflection is there is some issue the way we are uploading it through this plug-in. May be comparing http request header should give some hint.

**Comment by Zargath** [comment]
Hello,

I've been digging into this for a little while now. I still have not been able to reproduce the issue. Even with the BOM provided. 

That being said, It's important to me we get to the bottom on what's going on. I found where the warning in DTrack is being created. The only possibility is [here](https://github.com/DependencyTrack/dependency-track/blob/f7ff2294c4c8932fda7b8d78a9e30e5fbf1913d5/src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java#L111).

That code is hit when the [following validation](https://github.com/CycloneDX/cyclonedx-core-java/blob/c24ff8bfbadf6fc2d2d8a3599863ac8001e1322c/src/main/java/org/cyclonedx/BomParserFactory.java#L59) fails. 
```
public static boolean looksLikeCycloneDX(final byte[] bytes) {
    final String bomString = new String(bytes, StandardCharsets.UTF_8);
    if (bomString.startsWith("<?xml") && bomString.contains("<bom") &&
        bomString.contains("http://cyclonedx.org/schema/bom")) {
        return true;
    }
    else {
        return bomString.startsWith("{") && bomString.contains("bomFormat") && bomString.contains("CycloneDX");
    }
}
```

I suspect what is happening is that the path to the BOM in the pipeline is not correct and the wrong file is being sent to Dependency Track. In the coming days I will add this validation to the extension to make sure only valid BOM files are submitted.

**Comment by iamrahul127** [comment]
Hi, Thank you for looking into this. I was looking for looksLikeCycloneDX method code. Now I know false is being returned from else part of this method. 

I will look into 'wrong file is being sent to DT' though I this chances of that happening are very low.

**Comment by iamrahul127** [comment]
Further update. I can see that there some '?' mark like character present at index 0 in my bom. VSCode screenshot as below.
Good BOM. Doesn't have '?' character at start of file. 

![image](https://user-images.githubusercontent.com/24877322/208297974-cd3f3fda-2909-4e52-8f8b-0c33e5ff967b.png)

Bad BOM. Look at first character highlighted by green. 

![image](https://user-images.githubusercontent.com/24877322/208297932-0da974e7-464a-4e75-813d-e8e7b8ff6d04.png)

I am creating multiple boms as I have multiple technology project. Merging it together using following code. 
`C:\cyclonedx\cyclonedx-win-x64.exe merge --input-files ./angularbom.json ./csharpbom.json --output-file ./finalbom.json --input-format json`

Then I am removing duplicate components using jq. Command as follow.
`jq '{ "bomFormat": .bomFormat, "specVersion": .specVersion, "serialNumber": .serialNumber, "version": .version, "metadata": {"tools": [(.metadata.tools | unique[])], "component": (.metadata.component)},"components": [(.components | unique[])],"dependencies": [(.dependencies | unique[])]}' -a ./finalbom.json | Out-File -Force -Encoding UTF8 ./bom.json`

This is where '?' is added at start. I have no clue how to fix it as of now. 

BUT strange fact is that, same file works fine with Bom Upload functionality of DT. Why is not working with this extension?

**Comment by iamrahul127** [comment]
Managed to solve it by using command line task instead of powershell in azure build pipeline. jq script look like below now.

`echo "Removing duplicates"
jq "{ "bomFormat": .bomFormat, "specVersion": .specVersion, "serialNumber": .serialNumber, "version": .version, "metadata": {"tools": [(.metadata.tools | unique[])], "component": (.metadata.component)},"components": [(.components | unique[])],"dependencies": [(.dependencies | unique[])]}" .\finalbom.json > .\bom.json
echo "Removed duplicates and actual bom.json generated"`

BUT I am still wondering why it was working with BOM Upload of DT but not using this extension. 

@daniel-anova PFA small utility code which helped me identifying issue with my BOM. I hope it helps you. I am not a JAVA developer so do not judge me by quality of code. :)

You will need to replace `C:\\someValidPath` in code and then you should be able to run the code. 
 
Code line  `bomString.contains("bomFormat") && bomString.contains("CycloneDX") && bomString.startsWith("{")` in utility should tell you the story. 

Steps to get code working.

1. Rename QuickStart..txt to .java
[QuickStart.txt](https://github.com/gsoft-inc/azure-pipelines-dependency-track/files/10253856/QuickStart.txt)

2. Add references to the packages highlighted in yellow as shown in below screenshot below.
![image](https://user-images.githubusercontent.com/24877322/208299832-36b826aa-c4de-4699-b22d-64426a1aef9b.png)

**Comment by danielpof** [comment]
Hi, I've run the tests and I've determined the issue with my bom.xml.

The generated file is a UTF-8 BOM file, which means it starts with `0xEF, 0xBB, 0xBF` 

![image](https://user-images.githubusercontent.com/71904581/208420780-6d84e00f-b336-4631-ae02-6fc37b9946fb.png)

That's the unknown character found in the beginning of the file. Saving the file with UTF-8 encoding removes the BOM header.

I will try to add a conversion step to my pipeline and will report back.

```powershell
Get-Content ./bom.xml | Set-Content -Encoding utf8 ./bom-no-bom.xml
```

Reference:

- https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-with-bom

**Comment by iamrahul127** [comment]
Great let me know if that helps.

**Comment by danielpof** [comment]
Converting the BOM encoding to `UTF8` seems to have solved my issue. I'm assuming CycloneDX will always output in `UTF8 BOM` so a more permanent/proper fix would, likely be to remove the BOM header when reading the file?

**Comment by iamrahul127** [comment]
Great to hear. In my case I stopped using powershell script and used commandline to run jq. Problem solved.

**Comment by Zargath** [comment]
Thank you for this! 

Reading the code in Dependnecy Track I found the difference between the PUT upload, which the extension uses, and the POST upload used by the interface. 

The PUT request [does this](https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/resources/v1/BomResource.java#L309):
```
final byte[] decoded = Base64.getDecoder().decode(encodedBomData);
final BomUploadEvent bomUploadEvent = new BomUploadEvent(project.getUuid(), decoded);
Event.dispatch(bomUploadEvent);
```

Where the POST request [does this](https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/resources/v1/BomResource.java#L329):
```
final byte[] content = IOUtils.toByteArray(new BOMInputStream((in)));
final BomUploadEvent bomUploadEvent = new BomUploadEvent(project.getUuid(), content);
Event.dispatch(bomUploadEvent);
```

The issue here is `new BOMInputStream((in))` default behaviour is to return the Stream without the BOM bytes. Where `Base64.getDecoder().decode(encodedBomData)` will return all the bytes including the BOM. 

I will attempt to recreate the issue and submit an issue to Dependency Track.

**Comment by iamrahul127** [comment]
Excellent finding. Thank you!!!

**Comment by Zargath** [comment]
Issue submitted to Dependency Track here: https://github.com/DependencyTrack/dependency-track/issues/2312
