### ISSUE TITLE
Allow Project Name & Version instead of Project ID

### ISSUE THREAD

**Issue by 37b** [gsoft-inc/azure-pipelines-dependency-track#33]
Currently, all API calls require a Project ID (UUID), which may not be known at runtime. The API optionally allows many requests to use the project name and version combination as the unique identifier for a project. 

Since not all API calls allow name/version combination, if a name and version is provided instead of a project ID, the first API call should be is to fetch the UUID for subsequent calls.

**Comment by Zargath** [comment]
This has been released with version 1.15.0. Thank you!
