### ISSUE TITLE
Trusted Certificate Authority

### ISSUE THREAD

**Issue by morganmccarley** [gsoft-inc/azure-pipelines-dependency-track#5]
Currently, if Dependency-Track is installed using HTTPS with an internally signed certificate, the dependency-track pipeline task doesn't have a way to trust the cert chain.  From the pipeline log:
Finished task execution with error - Error: Uploading the BOM to Dependency Track Failed: {"code":"SELF_SIGNED_CERT_IN_CHAIN"}
##[error]Uploading the BOM to Dependency Track Failed: {"code":"SELF_SIGNED_CERT_IN_CHAIN"}

Given that many organizations will want to keep their security tools internal and use their own CA, I think this task should allow for either the injection of a certificate chain or a directory path to a chain as part of the configuration.

**Comment by Zargath** [comment]
Hi Morgan,

Thanks for submitting this issue. I will have a look to see if I can't reproduce your issue this week and get back to you quickly.

Thanks

**Comment by morganmccarley** [comment]
Thank you Edouard,
I did a little research and found this,
https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file.

Nodejs allows for adding certificates using a process environment variable.

morgan

**Comment by Zargath** [comment]
Oh! That might be a good alternative. Setting a variable in your pipeline should set an environment variable with the path to your CA. Alternatively, a more dynamic approach like a Powershell script could do it (https://stackoverflow.com/questions/56855546/azure-devops-server-pipeline-build-fails-when-using-self-signed-ssl-certificate).

If that doesn't work, setting the cert in the request to DTrack might work as well.

Thanks,
Edouard

**Comment by Zargath** [comment]
@morganmccarley I've release a new version that should fix your issue. Can you validate it please?

**Comment by morganmccarley** [comment]
Thank you Edouard, I had a brief delay in testing, the cert file on the
build server wasn't readable by the pipeline task so I had to submit a
ticket to our DevOps team to get that modified.  I've tested your solution
and it's working perfectly now!

**Comment by Zargath** [comment]
Hi Morgan, That's great! I'm happy to hear everything is working for you now :) Thanks for the follow up!
